{
  "uid": "89b137a11bad3071",
  "name": "test_add1[a-b-c]",
  "fullName": "test_calc.TestCalc#test_add1",
  "historyId": "6b4525be6cb1dc7ad00b1bba05638754",
  "time": {
    "start": 1607026873570,
    "stop": 1607026873576,
    "duration": 6
  },
  "status": "failed",
  "statusMessage": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_calc.py:40: AssumptionFailure\n>>\tpytest.assume(get_calc.add(a, b) == expect)\nAssertionError: assert False",
  "statusTrace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_calc.py:40: AssumptionFailure\nE               >>\tpytest.assume(get_calc.add(a, b) == expect)\nE               AssertionError: assert False\n\n/usr/local/lib/python3.8/site-packages/six.py:702: FailedAssumption",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [
    {
      "name": "module_feature",
      "time": {
        "start": 1607026873309,
        "stop": 1607026873309,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "stepsCount": 0,
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "hasContent": false
    },
    {
      "name": "get_calc",
      "time": {
        "start": 1607026873309,
        "stop": 1607026873309,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "stepsCount": 0,
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "hasContent": false
    }
  ],
  "afterStages": [
    {
      "name": "module_feature::0",
      "time": {
        "start": 1607026873696,
        "stop": 1607026873696,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "stepsCount": 0,
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "hasContent": false
    },
    {
      "name": "get_calc::0",
      "time": {
        "start": 1607026873695,
        "stop": 1607026873695,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "stepsCount": 0,
      "attachmentsCount": 0,
      "shouldDisplayMessage": false,
      "hasContent": false
    }
  ],
  "labels": [
    {
      "name": "feature",
      "value": "测试计算器的类"
    },
    {
      "name": "story",
      "value": "加法_异常case1"
    },
    {
      "name": "suite",
      "value": "test_calc"
    },
    {
      "name": "subSuite",
      "value": "TestCalc"
    },
    {
      "name": "host",
      "value": "FVFWF066HV2J.local"
    },
    {
      "name": "thread",
      "value": "37161-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "test_calc"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [
    {
      "name": "a",
      "value": "'a'"
    },
    {
      "name": "b",
      "value": "'b'"
    },
    {
      "name": "expect",
      "value": "'c'"
    }
  ],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "normal",
    "retries": [],
    "categories": [
      {
        "name": "Product defects",
        "matchedStatuses": [],
        "flaky": false
      }
    ],
    "tags": []
  },
  "source": "89b137a11bad3071.json",
  "parameterValues": [
    "'a'",
    "'b'",
    "'c'"
  ]
}